language: objective-c
xcode_project: KContinuousIntegration/KContinuousIntegration.xcodeproj 
xcode_scheme: KContinuousIntegration
osx_image: xcode10.2

script:
- set -o pipefail
- xcodebuild test -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -destination "name=iPhone 7" -enableCodeCoverage YES | xcpretty

after_success:
- bash <(curl -s https://codecov.io/bash)
